[open.aliases]
i = "ibis"
z = "zulip"
s = "search"
e = "email"
c = "cal"
d = "drive"
g = "github"
y = "youtube"
gh = "github"
ym = "youtubemusic"
io = "dkdcio"
key = "keyboard"
read = "kindle"
chat = "claude"
music = "youtubemusic"
cloud = "hetzner"
router = "mobilerouter"

## work
a = "ascend"
docs = "ascenddocs"
app = "ascendapp"
applocal = "ascendapplocal"
travel = "navan"
dbx = "databricks"
snow = "snowflake"

[open.things]
# websites
cal = "https://calendar.google.com"
ibis = "https://ibis-project.org"
dkdc = "https://dkdc.dev"
dkdcio = "https://dkdc.io"
drive = "https://drive.google.com"
email = "https://mail.google.com"
search = "https://google.com"
github = "https://github.com"
keyboard = "https://configure.zsa.io/moonlander"
youtube = "https://youtube.com"
youtubemusic = "https://music.youtube.com"
copilot = "https://github.com/copilot"
reader = "https://read.readwise.io"

kindle = "https://read.amazon.com"
audible = "https://audible.com"

## apps
edge = "/Applications/Microsoft Edge.app"
zulip = "/Applications/Zulip.app"

## cloud/work
aws = "https://us-east-2.console.aws.amazon.com/console"
gcp = "https://console.cloud.google.com"
azure = "https://portal.azure.com"
openai = "https://platform.openai.com/docs/overview"
claude = "https://claude.ai"
hetzner = "https://konsoleh.hetzner.com"

## work
ascend = "https://ascend.io"
ascenddocs = "https://docs.ascend.io"
ascendapp = "https://cody.app-dev.ascend.io"
ascendapplocal = "https://instance.app.local.ascend.dev"
onboarding = "https://ascend-io.monday.com/boards/8159119882"
figma = "https://www.figma.com/files/team/1306015839984154034"
monday = "https://ascend-io.monday.com"
inception = "https://ascend-io.monday.com/boards/5622713154/views/161790999"
expense = "https://www.expensify.com/inbox"
fabric = "https://app.fabric.microsoft.com"
miro = "https://miro.com/app/dashboard"
ashby = "https://app.ashbyhq.com"
inbox = "https://ascend-io.monday.com/boards/5622713154/views/162719659"
standup = "https://ascend-io.monday.com/overviews/15409312"
navan = "https://app.navan.com"
snowflake = "https://app.snowflake.com"
databricks = "https://dbc-386e5cd3-1860.cloud.databricks.com"
lunch = "https://forkable.com/mc"
clockwise = "https://www.getclockwise.com/app"

product = "https://studious-adventure-8qowop4.pages.github.io"
cnotes = "https://studious-adventure-8qowop4.pages.github.io/customer-meetings"

board = "https://github.com/orgs/ascend-io/projects/5"

## misc
mobilerouter = "http://192.168.8.1"

